$kind: http-request
url: http://localhost:9000/api/v1/roles/:id
method: PATCH
pathVariables:
  id: "1"
body:
  type: json
  content: "{\r

    \    \"name\": \"root\",\r

    \    \"description\": \"Quản trị hệ thống!!!\"\r

    }"
order: 3791093912888483
